apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2024-03-03T13:26:02Z"
  generation: 1
  labels:
    app: ms-payment-service
  name: ms-payment-service
  namespace: default
  resourceVersion: "658307"
  uid: 2047648a-0d7f-4b6a-b30b-59449248cabf
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ms-payment-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-payment-service
    spec:
      containers:
      - image: darshana991/ms-payment-service:latest
        ports:
          - containerPort: 9091
        imagePullPolicy: Always
        name: ms-payment-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-03-03T13:26:02Z"
    lastUpdateTime: "2024-03-03T13:38:23Z"
    message: ReplicaSet "ms-payment-service-7bd5dbf555" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-03-03T14:10:06Z"
    lastUpdateTime: "2024-03-03T14:10:06Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
